spring:
  application:
    name: go-routex-platform-core
  main:
    allow-bean-definition-overriding: false
    lazy-initialization: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  data:
    redis:
      host: ${APP_REDIS_HOST:localhost}
      port: ${APP_REDIS_PORT:6379}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/goroutex_platform_core}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:none}
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:10MB}

server:
  port: ${SERVER_PORT:8080}

grpc:
  server:
    port: ${GRPC_SERVER_PORT:9090}
  client:
    merchantService:
      address: ${MERCHANT_SERVICE_GRPC_ADDRESS:static://localhost:9090}
      negotiationType: plaintext
    bookingService:
      address: ${BOOKING_SERVICE_GRPC_ADDRESS:static://localhost:9090}
      negotiationType: plaintext
    paymentService:
      address: ${PAYMENT_SERVICE_GRPC_ADDRESS:static://localhost:9090}
      negotiationType: plaintext
    userService:
      address: ${USER_SERVICE_GRPC_ADDRESS:static://localhost:9091}
      negotiationType: plaintext

kafka:
  retry:
    back-off-ms: ${KAFKA_RETRY_BACK_OFF_MS:1000}
    back-off-multiplier: ${KAFKA_RETRY_BACK_OFF_MULTIPLIER:2.0}
    max-attempts: ${KAFKA_RETRY_MAX_ATTEMPTS:3}
    max-interval: ${KAFKA_RETRY_MAX_INTERVAL:10000}

media:
  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME:}
    api-key: ${CLOUDINARY_API_KEY:}
    api-secret: ${CLOUDINARY_API_SECRET:}

booking:
  hold-expiration:
    fixed-delay-ms: ${BOOKING_HOLD_EXPIRATION_FIXED_DELAY_MS:15000}
    initial-delay-ms: ${BOOKING_HOLD_EXPIRATION_INITIAL_DELAY_MS:15000}
    batch-size: ${BOOKING_HOLD_EXPIRATION_BATCH_SIZE:100}

clients:
  merchant-platform:
    base-url: ${MERCHANT_PLATFORM_BASE_URL:http://localhost:8080/api/v1/merchant-service/internal}
  payment-service:
    base-url: ${PAYMENT_SERVICE_BASE_URL:http://localhost:8080/api/v1/payment-service/internal}
  user-service:
    base-url: ${USER_SERVICE_BASE_URL:http://localhost:8080/api/v1/user-service/internal}

logging:
  level:
    root: INFO
    org.springframework.kafka: INFO
    org.apache.kafka: WARN
