spring:
  application:
    name: go-routex-management-service

  threads:
    virtual:
      enabled: true

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 1
        compression.type: gzip
        linger.ms: 10

    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "vn.com.*"
        spring.json.use.type.headers: false
        session.timeout.ms: 30000
        max.poll.records: 500

    events:
      trip-ready-for-sale: "routex.trip.ready-for-sale"
      trip-assigned: "routex.trip.assigned"
      notification-email: "routex.notification.email"
      notification-sms: "routex.notification.sms"

    topics:
      trips: "trip.management.event"
      routes: "route.management.event"
      booking: "route.bookings.event"

    group-id:
      trips: "management-service-trips"
      bookings: "management-service-bookings"
      payments: "management-service-payments"

    listener:
      ack-mode: manual

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    mapper:
      sort-properties-alphabetically: false

  servlet:
    multipart:
      max-file-size: ${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE:10MB}
      max-request-size: ${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE:12MB}

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

server:
  port: ${SERVER_PORT:8082}

locking:
  batch: 100

scheduled:
  polling:
    time: 500

identity:
  jwt:
    secret: ${JWT_SECRET:CZZRadv0Xe8z3stWFWYdtiJ2E86gUgJvFEfbCYFgJhQ}
    issuer: ${JWT_ISSUER:user-service}
    audience: ${JWT_AUDIENCE:management-service}
    authority-claim-name: ${JWT_CLAIM_NAME:roles}
    authority-prefix: ${JWT_AUTH_PREFIX:ROLE_}

media:
  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME:difqcci0j}
    api-key: ${CLOUDINARY_API_KEY:478878615354358}
    api-secret: ${CLOUDINARY_API_SECRET:EpU_ybF0PBin-qKQ6gDgzPHPEMc}
    default-folder: ${CLOUDINARY_DEFAULT_FOLDER:goroutex/}
    secure: ${CLOUDINARY_SECURE:true}


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.kafka: INFO
    org.apache.kafka: WARN

clients:
  merchant-platform:
    base-url: ${MERCHANT_PLATFORM_BASE_URL:http://localhost:8080/api/v1/merchant-service/internal}
  user-service:
    base-url: ${USER_SERVICE_BASE_URL:http://localhost:8080/api/v1/user-service/internal}

grpc:
  client:
    merchantService:
      address: ${MERCHANT_SERVICE_GRPC_ADDRESS:static://localhost:9090}
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    userService:
      address: ${USER_SERVICE_GRPC_ADDRESS:static://localhost:9091}
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
